apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "locust-tests.fullname" . }}
  labels:
    {{- include "locust-tests.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
